name=SimpleCANio
version=1.0.0
author=simplefoc
maintainer=simplefoc
sentence=Arduino library for a Simple CAN Abstraction for stm32 and esp32 devices
paragraph=Support for stm32, esp32 and providing a helper for any generic CAN controller. 
category=Communication
url=https://github.com/simplefoc/SimpleCANio
architectures=stm32
includes=SimpleCANio.h
